layout:
  preset: catalog-sidebar
  blocks:
    about:
      enabled: true
      placements:
        - sidebar
    news:
      enabled: true
      placements:
        - sidebar
      count: 3
    collections:
      enabled: true
      placements:
        - sidebar
    catalog:
      enabled: true
      placements:
        - main
